### ISSUE TITLE
'labels' special function doesnt add a return statement if one is not present

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/varjo#1]
This is quite a pain in the backside as, while it gets caught by the driver's compiler, it is not very lispy.

The tricky bit though is if a function has a return type of :none (e.g. with for loops) then where do we put the return? Example below shows the generated code

    VARJO> (cgl:defprogram? prog-1 ((a :int) (b :vec3))
                        (:vertex (labels ((test ((x :int)) (* x 10))) 
                                           (test a))))

    #vertex-shader
    #version 330

    layout(location=0) in int a;
    layout(location=1) in vec3 b;

    int _ftest(int x) {
        (x * 10);
    }

    void main() {
        _ftest(a);
    }

**Comment by byulparan** [comment]
how to use "labels" in defpipeline?

(defpipeline prog-1 ((pos :vec3) &uniform (a :float))
  (:vertex
   (setf gl-position (v! pos 1.0)))
  (:fragment
   (labels ((fun ((x :float))
	      (return (* x x))))
     (out out-color (v! 1.0 1.0 1.0 (fun a))))))

but this code error  "Varjo: No function called 'FUN' was found in this environment"
If I don't calling "fun", compiled OK.

float fun_80v(float x_79v);

float fun_80v(float x_79v) {
return (x_79v * x_79v);
} 

I don't use cepl(just need varjo), please add some example to varjo...
sorry, My english is ugly.. but varjo is very useful for me!

**Comment by cbaggers** [comment]
--addressed this in email--
