### ISSUE TITLE
readme: it claims that glsl >= 120 is supported

### ISSUE THREAD

**Issue by dkochmanski** [cbaggers/varjo#10]
but quick grepping through sources indicates, that the minimal supported version is 330

**Comment by dkochmanski** [comment]
Main motivation to support something little older is ability to work with mesa (software rendering and OSS gfx drivers)

**Comment by cbaggers** [comment]
You're totally right, I'll remove that from the readme

the default if unspecified will be 330 and cepl probably has 3.2 as it's minimal version. Varjo itself should be able to handle older version, but I need to go update all the version info on all the functions.
I have parsed glsl into data https://github.com/cbaggers/gl-to-sexp/tree/master/spec so this should be possible now, but I need to put in the time.

Sorry this doesnt work for you yet, if you want to hack and see you could try replacing `(:330 :440)` with `(:120 :330 :440)` across the project, but your millage will seriously vary :)
