### ISSUE TITLE
Rename def* to define-* For SLIME Markup Compatibility

### ISSUE THREAD

**Issue by Shinmera** [cbaggers/varjo#115]
SLIME automatically highlights calls to functions with a `define-` prefix.

**Comment by cbaggers** [comment]
Good point, I've switched to doing this with my newer code.

I think I'll replace the internal macros with this now, and deprecate the ones that are part of the public api.

**Comment by cbaggers** [comment]
Done.
We still have the `v-def*` macros though, which are looking increasingly ugly to me. Will add a new issue for that.

**Comment by Shinmera** [comment]
Great! :)

**Comment by cbaggers** [comment]
Gonna go all in on this, adding `define` versions of all the `v-def` macros
