### ISSUE TITLE
Allow discard in fragment stage

### ISSUE THREAD

**Issue by porky11** [cbaggers/varjo#120]
Discard in fragment shader doesn't seem to work.
I thought, when not returning a value it would work, but then I get the error, that different types are returned.

**Comment by cbaggers** [comment]
Hi @porky11, long time no see.
Thanks for reporting this.

**Comment by porky11** [comment]
Yo, wasn't interested in lisp that much anymore, but mainly in low level languages, but in lisp it's easier to get something done often. And CEPL also seams like a very nice way to use opengl, and with your new videos i also understand, how to use it.

**Comment by cbaggers** [comment]
We will need to add a `discarded` type and work out how to handle it in the context of varjo's implicit returns. For example:

```
(if foo
    (discard)
    (v! 1 2 3 4))
```
This is fine glsl but if this is in the tail position then the type of the `if` expression is `(or :void :vec4)` which isn't a valid return type. However this is nonsensical as once `discard` is hit there is no more execution so there is no return type.

So the `discarded` type will have special rules to ensure that:
- it is valid as the primary return in a frag shader (as long as there are no other return types)
- `if` statements return `foo` rather than `(or discarded foo)` in the case of discard.

From the glsl spec v4.5:

> The discard keyword is only allowed within fragment shaders. It can be
> used within a fragment shader to abandon the operation on the current
> fragment. This keyword causes the fragment to be discarded and no
> updates to any buffers will occur. Control flow exits the shader, and
> subsequent implicit or explicit derivatives are undefined when this
> exit is non-uniform. It would typically be used within a conditional
> statement, for example:
> 
> 	if (intensity < 0.0)
> 		discard;
> 
> A fragment shader may test a fragment’s alpha value and discard the
> fragment based on that test. However, it should be noted that coverage
> testing occurs after the fragment shader runs, and the coverage test
> can change the alpha value.
> The return jump causes immediate exit of the current function. If it
> has expression then that is the return value for the function.
> The function main can use return. This simply causes main to exit in
> the same way as when the end of the function had been reached. It does
> not imply a use of discard in a fragment shader. Using return in main
> before defining outputs will have the same behavior as reaching the
> end of main before defining outputs.

**Comment by cbaggers** [comment]
```
TESTS> (glsl-code (translate (make-stage :fragment
                                         nil
                                         '((b :int))
                                         nil
                                         '((if (< b 10)
                                               (discard)
                                               (v! 1 2 3 b))))))
"// fragment-stage
#version 450

layout(location = 0)  out vec4 _FRAGMENT_STAGE_OUT_0;

uniform int B;

void main()
{
    vec4 tmp7280;
    if ((B < 10))
    {
        discard;
    }
    else
    {
        tmp7280 = vec4(float(1),float(2),float(3),float(B));
    }
    vec4 g_GEXPR07282 = tmp7280;
    _FRAGMENT_STAGE_OUT_0 = g_GEXPR07282;
    return;
}
"
```

Merged basic support into master. No tests in the suite covering this yet so I wouldnt be surprised to see issues arise (especially when interacting with return & emit). However we have a base for the feature now and other issues will be separate issues
