### ISSUE TITLE
'if' always need else-case? 

### ISSUE THREAD

**Issue by byulparan** [cbaggers/varjo#13]
(if (> a 2.0) (setf b 4.0))    

expression error "Type mismatch: else-case is nil which is of bool type, yet the then form is of VARJO:V-FLOAT type."  

so I always made dummy else-case.... 
maybe this is not bug...but I want more clear code...
and result of then-case, else-case sholud be same type.

in glsl  "if" is not expression unlike lisp. so sometimes I just use "%if".
but "%if"  generate "NIL" string in result glsl code when nested "%if".

**Comment by cbaggers** [comment]
thanks for the report, which branch is this on?

**Comment by byulparan** [comment]
I don't know about git. but...

    git branch -v
    =>* master dfbdacf struct type dependencies + bug fixes

Is it enough?

**Comment by cbaggers** [comment]
Yes, I have been working on a different branch for the last few months. I have just merged it to master. This new version is also available through quicklisp now.

You will need to `:use` the varjo-lang package. 

To write an `if` without an else use `%if` 

```
        (defshader meh ()
	   (let ((a 1.0) (b 2.0))
	     (%if (> a 2.0)
		  (setf b 4.0))
	     (v! 0 0 0 0)))
```

**Comment by byulparan** [comment]
in nested  `%if`  have problem.

    (varjo::glsl-code 
     (varjo::defshader meh ()
       (let ((a 1.0) (b 2.0))
         (%if (> a 2.0)
	      (%if (< b 2.0) (setf b 4.0)
	           (setf b 1.0)))
         (v! 0 0 0 0))))

result glsl code is

    #version 330
    void main() {
      float A_129V = 1.0f;
      float B_130V = 2.0f;
      if ((A_129V > 2.0f)) {
        if ((B_130V < 2.0f)) {
          B_130V = 4.0f;
        } else {
          B_130V = 1.0f;
        }
     NIL                                               //  <= what?
    }
    gl_Position = vec4(0,0,0,0);
    }


currently I study hard shader use Varjo. Thank you!

**Comment by cbaggers** [comment]
Wow, that is embarrassing! Thankyou for finding this, I will fix it very
soon

**Comment by cbaggers** [comment]
Pushed a fix for this: https://github.com/cbaggers/varjo/commit/b069ded0fab20dffb347351575bc4c8e2b2f3270
