### ISSUE TITLE
v-defstruct doesn't generate a proper struct accessor when the accessor name is not given 

### ISSUE THREAD

**Issue by djeis97** [cbaggers/varjo#132]
```lisp
(v-defstruct foo
  (bar :int))
```
Generates an accessor `foo-bar` with the glsl format string `~a.FOO_BAR`, despite the slot being named just `BAR`. If the accessor name is given explicitly then this is used as the glsl slot name too, which returns everything to consistency, but the format string is always generated from the accessor name while the slot name in the struct definition is only generated from the accessor name if it is passed. CEPL always passes the name of the accessor explicitly, even when it is not supplied in `cepl:defstruct-g`, which hides this bug.

**Comment by djeis97** [comment]
Personally I feel like the GLSL name should always be based off the v-defstruct slot name, but either way it's important that the generated glsl from the accessor match the actual struct definition.

**Comment by cbaggers** [comment]
Agreed, I think this should be behaving in master now, would you mind checking?

**Comment by djeis97** [comment]
Seems to be working properly. I tested with:
```lisp
(v-defstruct test ()
  (a :int)
  (b :int :accessor b-accessor))
(let ((type (type-spec->type 'test)))
  (print (v-slots type))
  (print (v-signature type)))
```

**Comment by cbaggers** [comment]
sweet, lets close this for now then. Thanks mate
