### ISSUE TITLE
recursive defstruct access can possibly generate wrong glsl code

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#133]
Let bindings for a recursive struct slot do not include the second struct's definition.

Given the following structs:

```lisp
(v-defstruct a-struct ()
  (a-slot :vec3 :accessor a-accessor))

(v-defstruct b-struct ()
(b-slot a-struct :accessor b-accessor))
```

Using it like the following only generates a struct definition for `B_STRUCT`, and not `A_STRUCT`, thus its generated code of `STRUCT.B_ACCESSOR.A_ACCESSOR` points to nothing:

```lisp
(let ((var (a-accessor (b-accessor struct)))) var)
```

However this DOES generate both definitions:

```lisp
(a-accessor (b-accessor struct))
```

The fact that a LET is used completely omits the required struct definition:

```lisp
struct A_STRUCT {
    vec3 A;
};
```

...making the generated code invalid.

**Comment by djeis97** [comment]
(Rewritten using just the plain varjo api)
This generates the proper struct definitions:
```lisp
(glsl-code (translate (make-stage :vertex
                                  nil
                                  '((b b-struct))
                                  nil
                                  '((a-accessor (b-accessor b))
                                    (vec4 1 0 0 1)))))
```
But this does not:
```lisp
(glsl-code (translate (make-stage :vertex
                                  nil
                                  '((b b-struct))
                                  nil
                                  '((let ((foo (a-accessor (b-accessor b))))
                                      foo)
                                    (vec4 1 0 0 1)))))
```

It's not just a problem with uniforms, either, as this works:
```lisp
(glsl-code (translate (make-stage :vertex
                                  '((b b-struct))
                                  nil
                                  nil
                                  '((a-accessor (b-accessor b))
                                    (vec4 1 0 0 1)))))
```
But this does not:
```lisp
(glsl-code (translate (make-stage :vertex
                                  '((b b-struct))
                                  nil
                                  nil
                                  '((let ((foo (a-accessor (b-accessor b))))
                                      foo)
                                    (vec4 1 0 0 1)))))
```

As a side note, I'm not sure that the third example is valid regardless- it does not break apart the nested struct into separate inputs- but that is unrelated to this particular bug (the missing declaration of `a-struct`).

**Comment by djeis97** [comment]
Combining both generates the right struct declaration, as with this:
```lisp
(glsl-code (translate (make-stage :vertex
                                  nil
                                  '((b b-struct))
                                  nil
                                  '((let ((foo (a-accessor (b-accessor b))))
                                      foo)
                                    (a-accessor (b-accessor b))
                                    (vec4 1 0 0 1)))))
```
Generates the right struct declarations, which implies it has more to do with failing to discover `a-struct` than with something filtering it out.

This further seems to be the case when you try it with neither, as:
```lisp
(glsl-code (translate (make-stage :vertex
                                  nil
                                  '((b b-struct))
                                  nil
                                  '((vec4 1 0 0 1)))))
```
Fails to generate the declaration for `a-struct`.

My guess is that varjo is neglecting to pull in `a-struct` when looking at the type of the `b` uniform, instead delaying until some other part of the compiler actually references it (and whether this referencing actually makes it all the way out to the code which generates the declarations seems a little hard to predict). Perhaps some code has to be added to eagerly check the component types of any argument in case they may be structs?

Interestingly this does actually generate the right declarations:
```lisp
(glsl-code (translate (make-stage :vertex
                                  nil
                                  '((b b-struct))
                                  nil
                                  '((let ((foo (b-accessor b)))
                                      foo)
                                    (vec4 1 0 0 1)))))
```

**Comment by djeis97** [comment]
I think I fixed it, by adding some code to recursively scan all the types mentioned in either the in-args or uniforms, but I'd suggest looking it over pretty carefully :sweat_smile:

**Comment by cbaggers** [comment]
@djeis97 & @mfiano thankyou! this is an excellent report. There might be two bugs here, depending on how I want this to work.

At one point I was very interested in being able to remove unused uniforms (which iirc is where the 'used type' tracking came from. I'd still like this but valid glsl with unused structs is way better than missing structs, so I will set that as first priority.

So bug 1 is that the let has an effect on the 'used types', that's a dumb bug. Bug 2 is that structs don't recursively include struct definitions and I think @djeis97 's PR will handle that (but I'll have a good read through it first, like he said :) ) sorry the code is so hairy in these projects :|

I'll get started on this tonight, doesnt *seem* to be too nasty so we should have a fix out in the january quicklisp release

**Comment by cbaggers** [comment]
https://github.com/cbaggers/varjo/pull/135 has the first part of the fix (bug 1)

**Comment by mfiano** [comment]
@Baggers I had a chance to try @djeis97's PR and indeed does fix the problem with the LET. It also solves another problem in that even without the LET, recursive struct access will put the definitions out of order in that STRUCT_A is referenced (in a slot of STRUCT_B) before it is even defined, which I'm pretty sure is also invalid GLSL. it works great for me.

**Comment by djeis97** [comment]
Before my third commit, structs containing arrays containing structs would cause problems because `order-structs-by-dependency` would get the actual array types instead of the struct element-types. Patching `order-structs-by-dependency` only pushed this problem further down the compilation process, so instead I had `find-used-user-structs` just extract the element-type itself when coming up with the list of used struct types.

**Comment by cbaggers** [comment]
My PR to @djeis97 's PR https://github.com/djeis97/varjo/pull/1 :)

**Comment by cbaggers** [comment]
Merged :) thanks again
