### ISSUE TITLE
Allow different glsl versions in different stages in same pipeline

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/varjo#139]
Apparently this is legal..who knew?

well @mfiano did for a start.

ok todo:
- find the part of the spec that confirms this and paste it here
- remove this restriction from rolling-translate

**Comment by mfiano** [comment]
`Shaders for the core or compatibility profiles that declare different versions can be linked together.  
However, es profile shaders cannot be linked with non-es profile shaders or with es profile shaders of a different version, or a link-time error will result.  When linking shaders of versions allowed by these rules, remaining link-time errors will be given as per the linking rules in the GLSL version corresponding to the 
version of the context the shaders are linked under.  Shader compile-time errors must still be given strictly based on the version declared (or defaulted to) within each shader.`

**Comment by cbaggers** [comment]
@mfiano nice one!

**Comment by cbaggers** [comment]
workaround is now in master for this.
