### ISSUE TITLE
mulitple-value-bind arguments issue.

### ISSUE THREAD

**Issue by byulparan** [cbaggers/varjo#14]
(varjo::defpipeline blah
        (:vertex ((pos :vec3) &uniform (a :float))
                     (values (v! pos 1.0) a))
        (:fragment ((hmm :float))
                    (labels ((fun ((x :float))
                             (values (* x x)
		         		                   10.0)))
               (multiple-value-bind (x y)
		             (fun a)
		         (v! x y  hmm a)))))

I use multiple-value-bind, then this code's result (main function) are

    void main() {
       float mvb-45v0;
       float mvb-45v1;
       mvb-45v0 = FUN_44V(A,mvb-45v0);  // <- maybe...second arg should be "mvb-45v1". right?
       OUTPUT_COLOR_47V = vec4(mvb-45v0,mvb-45v1,OUT_40V,A);
    }

**Comment by cbaggers** [comment]
Thanks for this report too, which branch is this?

**Comment by cbaggers** [comment]
Yes! you are correct, that was a bug. It is now fixed in master

**Comment by byulparan** [comment]
oh! one more thing!  "mvb-20v0" is invalid naming.  
It should be "mvb20v0" or "mvb_20v0".

**Comment by cbaggers** [comment]
Argh! I need better tests! Thankyou for finding this, I'll fix this soon

**Comment by cbaggers** [comment]
Pushed a fix for this: https://github.com/cbaggers/varjo/commit/6209014707eac09e51cd0a0b5e03f6cf25410865
