### ISSUE TITLE
Opaque types cannot be used in interface blocks

### ISSUE THREAD

**Issue by cbaggers** [cbaggers/varjo#146]
This affects ubos & ssbos. In this case it was samplers in a ubo

```
error C7554: OpenGL requires sampler variables to be explicitly declared as uniform
error C7554: OpenGL requires sampler variables to be explicitly declared as uniform
```

Todo:
- add a v-opaque supertype for sampler, etc
- add a check for the principle issue

**Comment by cbaggers** [comment]
Fixed on master

**Comment by mfiano** [comment]
I haven't actually tested this yet, but something came to mind: Does your fix prevent uniform block structs from containing other structs that have opaque types, etc recursively, or is this only a fix for direct members of an interface block?

**Comment by cbaggers** [comment]
Yup it's recursive.
