### ISSUE TITLE
ubo uniform qualifier generates uniform block and struct

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#149]
I'm not sure if this is a bug, but this doesn't seem right. If you add the `:ubo` qualifier to a struct uniform to generate a uniform block, the generated GLSL code has both a uniform block definition AND a struct definition like:

```glsl
#version 330

struct FOO_STRUCT {
    int DATA1;
    int DATA2;
};

layout(std140) uniform _UBO_FOO
{
    int DATA1;
    int DATA2;
} FOO;
```

**Comment by cbaggers** [comment]
Thanks, it is a bug but a rather benign one. Varjo should not be emitting that code, but it also doesnt hurt that it does

**Comment by djeis97** [comment]
I’m pretty sure this is a side-effect of the way we patched the other struct declaration bug- now varjo is a bit too eager emitting the struct declarations for uniform args.

**Comment by cbaggers** [comment]
Certainly could be more frequent now, however I remember seeing this previously too

**Comment by cbaggers** [comment]
I think i've got this fixed. I'm going to merge to master real soon. If I hear of bugs from folks using this I wont merge it to quicklisp this month and I'll make this a testing month instead, so far all my code & projects are working.

**Comment by mfiano** [comment]
I will be testing Shadow this week. I'll let you know if I experience any bugs from this streak of bug fixes. Way to go!
