### ISSUE TITLE
Add implicit ubo/ssbo layout to qualifiers slot

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#152]
When a uniform struct is given `:ubo` or `:ssbo` without an explicit packing layout, `:std-140` is implied in the glsl source. I request that when left out, we explicitly add it to the qualifiers slot so that it can be queried from lisp.

**Comment by cbaggers** [comment]
Agreed. I'd like to do this in `#'make-stage` so it can be reviewed before being passed to translate.
I wonder what other things we can expand here.

Thanks for the issue report

**Comment by cbaggers** [comment]
Fixed on feature/remove-qualifiers-from-vars
