### ISSUE TITLE
How do I access matrix columns?

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#164]
How do I access the columns of a mat3 for example, as vec3's? In GLSL I could do m[0], m[1], or m[2] on a mat3 and get back vec3's. It seems I can't use aref on a matrix so I was wondering how I am able to do this in order to test my matrices written to SSBOs contain the right data (using them for frag output to test). Thanks

**Comment by cbaggers** [comment]
Yeah this is a place where CL just doesnt have an equivalent. We could just make vari's aref handle this or we add something else. 

I think maybe we just used aref as then its only weird to lispers whereas some other func will be weird for everyone

**Comment by mfiano** [comment]
Tested the latest commit, 4ecc88 and it works good for some time, so closing this
