### ISSUE TITLE
Defining functions for compute shaders

### ISSUE THREAD

**Issue by tsili** [cbaggers/varjo#167]
How am I supposed to define my own non-stage functions for compute shaders. Below I have an example of what I thought would work but doesn't.

(ql:quickload :cepl)
(ql:quickload :cepl.sdl2)
(ql:quickload :rtg-math)

(defpackage test
           (:use :cl
                 :cepl
                 :rtg-math
                 :vari))

(in-package :test)

(defvar *data* nil)
(defvar *ssbo* nil)

(defstruct-g (bah :layout :std-430)
  (data (:int 10)))

(defun-g dummy-fun ()
  t)

(defmacro-g dummy-mac ()
  t)

(defun-g yay-compute (&uniform (woop bah :ssbo))
  (declare (local-size :x 1 :y 1 :z 1))
  (setf (aref (bah-data woop) (int (x gl-work-group-id)))
        (int (x gl-work-group-id)))
  (dummy-mac) ; works
  (dummy-fun) ; doesn't work with error on compile
  (values))

;; Varjo: Compilation Failed:
;;
;; Stages: VERTEX TESSELLATION-CONTROL TESSELLATION-EVALUATION GEOMETRY FRAGMENT
;; Varjo: Symbol 'GL-WORK-GROUP-ID' is unidentified.
;;
;; Stages: COMPUTE
;; Varjo: Compute stages must return (values) however DUMMY-FUN returns:
;; (#<V-BOOL {103CB947D3}>)
;;    [Condition of type VARJO-CONDITIONS:TEST-TRANSLATE-FAILED]

(defpipeline-g test-compute ()
  :compute yay-compute)

(defun reset ()
  (setf *data* (make-gpu-array nil :dimensions 1 :element-type 'bah))
  (setf *ssbo* (make-ssbo *data*)))

(defun test ()
  (reset)
  (map-g #'test-compute (make-compute-space 10)
         :woop *ssbo*))

;; In repl
(reset)
(test)
(pull-g *data*) ; --> (((0 1 2 3 4 5 6 7 8 9)))

As can be seen, the macro variant of the same functionality works where the function does not. I have seen this cond of definition to work on vertex/fragment shaders in the cepl.examples. Are compute shaders supposed to work differently in this manner by using macros or is there something I'm missing?

**Comment by cbaggers** [comment]
Thankyou for this report, it's absolutely a bug, and a dumb one too.

this form in `make-function.lisp` is the issue:
```
      (when (typep (stage env) 'compute-stage)
        (assert (null return-set) () 'compute-stage-must-be-void
                :name name :returns return-set))
```
We could just change `when (typep (stage env) 'compute-stage)` to `when (and (typep (stage env) 'compute-stage) mainp)` and I think this will help but I expect this really needs to be moved in the stage validation code later in the compilation.

I'll get this fixed properly this week, but in the meantime if you could try the change mentioned above it would be really interesting to hear if that helped.

Sorry for the bug, but thanks again for reporting it

**Comment by cbaggers** [comment]
Fixed here https://github.com/cbaggers/varjo/commit/64061686f902c5c9c6b14972cb9b68bc609784c6
