### ISSUE TITLE
loop bug.

### ISSUE THREAD

**Issue by byulparan** [cbaggers/varjo#17]
(varjo::defpipeline test-pipeline
      (:vertex ((pos :vec2))
	       (values (v! pos 0.0 1.0)))
      (:fragment nil
	         (labels ((op-u ((d1 :vec2) (d2 :vec2))
		    	          (let* ((result (v! .0 .0)))
			                (if (< (x d1) (x d2)) (setf result d1)
			                    (setf result d2))
    			            result))
	    	             (foo ((pos :vec3))
			                 (let* ((pd pos)
			                          (d (v! 0.0 0.0)))
			                    (for (i 0) (< i 5) (setf i (+ i 1))
			                          (setf d (op-u d (v! 1.0 1.0))))
			                     d)))
	              (v! (foo (v! 1.0 1.0 1.0)) 0.0 1.0))))

It's meanless (or invalid) code. but....I get this error message

    Varjo's flow analyzer has been unable to resolve the variable flow in this
    loop within a reasonable ammount of time. This counts as a compiler bug so
    please report it on github

so I report it. :-)  maybe...This error generate in "for" loop.

**Comment by cbaggers** [comment]
thankyou @byulparan, I will look at this as soon as possible.

**Comment by cbaggers** [comment]
Hi @byulparan, I have just run this code and I do not get the error.

I did the following steps:
- pull master
- `(ql:quickload :varjo)`
- `(in-package :varjo)`
- paste your code
- hit return

The result I got was:

```
"#version 330

layout(location = 0) in vec2 POS;

void main() {
vec4 V_TMP_29V_30V = vec4(POS,0.0f,1.0f);
gl_Position = V_TMP_29V_30V;
}


#version 330

layout(location = 0) out vec4 OUTPUT_COLOR_42V;

vec2 OP_U_36V(vec2 D1_31V, vec2 D2_32V);
vec2 FOO_41V(vec3 POS_37V);

vec2 OP_U_36V(vec2 D1_31V, vec2 D2_32V) {
vec2 RESULT_33V = vec2(0.0f,0.0f);
vec2 RESULT_FROM_IF_34V_35V;
if ((D1_31V.x < D2_32V.x)) {
RESULT_FROM_IF_34V_35V = RESULT_33V = D1_31V;
} else {
RESULT_FROM_IF_34V_35V = RESULT_33V = D2_32V;
}
RESULT_FROM_IF_34V_35V;
return RESULT_33V;
}

vec2 FOO_41V(vec3 POS_37V) {
vec3 PD_38V = POS_37V;
vec2 D_39V = vec2(0.0f,0.0f);
for (int I_40V = 0;(I_40V < 5);I_40V = (I_40V + 1)) {

D_39V = OP_U_36V(D_39V,vec2(1.0f,1.0f));
}
return D_39V;
}

void main() {
OUTPUT_COLOR_42V = vec4(FOO_41V(vec3(1.0f,1.0f,1.0f)),0.0f,1.0f);
}
"
```

Is this error still occurring for you?

**Comment by byulparan** [comment]
ah! sorry. I use `%if` instead `if` in op-u function(labels)
when I use `if` no get error. but `%if` get the error... curious..

**Comment by cbaggers** [comment]
Oh that is interesting :) Thanks I will look at that

**Comment by cbaggers** [comment]
Hmm something is very wrong here :p 

I have made a smaller example that causes the issue

```
(varjo::defshader test ()
  (let ((d (v! 0 0)))
    (for (i 0) (< i 5) (incf i)
         (%if (< (x d) (y d))
              (setf d d)
              (setf d d)))
    (v! 0 0 0 0)))
```

Now to work out what is broken.

**Comment by cbaggers** [comment]
ooh exciting this may be multiple bugs. Found one, I'll fix it and then test the original again :)

**Comment by cbaggers** [comment]
Yes! there are more bugs. The smaller example is now working. See here https://github.com/cbaggers/varjo/issues/19 for the ticket.

This did not fix the original problem so lets try find more issues

**Comment by cbaggers** [comment]
Found a place were the compiler errored instead of giving a nice error message #20

**Comment by cbaggers** [comment]
Writing up some details as I work through this. You dont have to read this, it's mostly to help me

```
(defshader test-pipeline ()
  (labels ((inner-func ((d1 :vec2) (d2 :vec2))
	     (let* ((result (v! 0 0)))
	       (%if (< (x d1) (x d2))
		    (setf result d1)
		    (setf result d2))
	       result)))
    (let* ((d (v! 0 0)))
      (for (i 0) (< i 5) (setf i (+ i 1))
	   (setf d (%peek (inner-func d (v! 1.0 1.0))))))
    (v! 0 0 0 0)))
```

Right so the flow analyzer has to work out where all the values go but
this is tricky when loops or if statements get involved.

Every value a flow-id. Most expressions return new values, thus have
new flow-ids.

A `setf` or `setq` replace the value and thus flow-id on the target
name.

In an `if` statement, we cant tell which arm of the `if` will run so
we say that the flow-id is the union of the two ids. So if the `then`
arm of the `if` gave `#<flow-id 1>` & the `else` arm gave `#<flow-id
2>` then the flow-id for the whole `if` expression is 
`#<flow-id 1 2>`.

It gets more complicated with loops. A loop in glsl doesnt have a
return so by default we can say no 'information' flows out of the
loop. However we can `setf` from inside a loop, at that point
information we care about will leave the loop.  We also cant tell (in
many cases) how long a loop will run for, so let's assume it will run
an unknowable number of times. What can we still do with this?

Well if a loop changes a variable `x` 1000000 times to a random number
then the flow-id is kind of boring, any of those flow-ids are as good
as another. When we think about this it becomes clear that we are
trying to find out when no new information leaves the loop. We also
see that values created inside the loop are equal, so once one is
dealt with the rest are not information. This also implies the
opposite, that the important information is the stuff that comes from
outside the loop.

So what we need to do is collect flow-ids until:
- no variable from outer scope changed (no information left the loop)

OR
- Nothing that was `setf`, was `setf` to a value from outside the
  scope (no information from outside flowed in)

**Comment by cbaggers** [comment]
Ok, I have a fix for this now. I'm not pushing it yet though as it needs some heavier testing. Going to rebuild some of the cepl examples (cepl makes heavy use of the flow analysis feature) and make sure everything still works.
