### ISSUE TITLE
- (and maybe +) operators are missing legal type rules

### ISSUE THREAD

**Issue by psilord** [cbaggers/varjo#185]
Hello,

I noticed that the vari operator minus (-) failed to understand how to subtract a floating point
number from a vec3. This should be legal GLSL code.

So, please add this to vari:

```lisp
(vari.glsl::v-def-glsl-template-fun - (a b) "(~a - ~a)"
	 (vari.types:v-vec3 vari.types:v-real) 0 :pure t)

;; and one for + too.
 (vari.glsl::v-def-glsl-template-fun + (a b) "(~a + ~a)"
	 (vari.types:v-vec3 vari.types:v-real) 0 :pure t)
```

Thank you!

**Comment by mfiano** [comment]
I can confirm there are a lot of template functions missing in this regard.

**Comment by cbaggers** [comment]
@psilord thanks, you are correct. I've been meaning to get this into glsl-spec for a while now so I have opened a ticket over [here](https://github.com/cbaggers/glsl-spec/issues/5). When they are added there I can remove all the definitions inside varjo and this will all be much more consistant.

**Comment by cbaggers** [comment]
@psilord I added some [more operator definitions](https://github.com/cbaggers/glsl-spec/blob/master/operators.lisp) to `glsl-spec` today. This takes care of this and other similar (unreported) issues.

I have not addressed type constructors yet as `glsl-spec`'s goal is to have fully enumerated definitions and there are too many permutations of valid arguments for matrix constructors for this to be a valid approach. I'll open another issue for the type constructors.

Feel free to close this if the changes suit your needs :)

**Comment by cbaggers** [comment]
Issues believed resolved. Matrix constructor issue being tracked here https://github.com/cbaggers/varjo/issues/209
