### ISSUE TITLE
int32 issue

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#193]
The recent changes that allow :int32/:uint32 type-spec's cause all sorts of issues with the Shadow library. The issue is that `:int` in vari shader programs is no longer translated to the `:int` type-spec after it is compiled. As an example:

```lisp
CL-USER> (varjo:type-spec->type :int)
#<VARI.TYPES:V-INT {10095DB903}>
CL-USER> (varjo:type->type-spec *)
:INT32
```

Whereas before this was transparent.

I'm not even sure why int32 was added. I can't find it in the GLSL docs. Regardless I think if a vari stage defines an `:int` type, it should be translated from v-int to an `:int` type spec to be consistent with GLSL and older functionality.

**Comment by cbaggers** [comment]
On this now

**Comment by cbaggers** [comment]
Fixed.

The reason `:int32` & `:uint32` were added is that they are valid cffi types who size are relevant to glsl. We care about cffi as that is where the colon naming came from originally. If we were being true to common lisp then the types should be `(signed-byte 32)`, however as this was being used closely with cl-opengl the cffi types seemed the most natural.

I must admit that nowerdays I probably would use the lisp types instead but so long as we are using the cffi names for the basic types it felt right to have the sized versions too (I believe there was also an issue raised requesting this at some point but my memory may be failing me)

**Comment by cbaggers** [comment]
To clarify, with the latest commit, the following behavior is seen:

```
TESTS> (type->type-spec (type-spec->type :int32))
:INT
TESTS> (type->type-spec (type-spec->type :int))
:INT
```
