### ISSUE TITLE
Opengl ES support?

### ISSUE THREAD

**Issue by v-a-1** [cbaggers/varjo#194]
I'm trying to use varjo to output shaders for opengl es. The only thing needed really is the header line which should be "# version 300 es". However there is no such supported version.

Is there a reason for this? Opengl es would naturally fit right in, considering it is a smaller subset.
I tried patching the *supported-versions* variable and add a version, but it seems to lead to other problems. I'm assuming the supported versions check against functions that are supported.

Could I use this with minimal changes for opengl es? or is it just not possible?

**Comment by cbaggers** [comment]
This is a duplicate issue, but you can see [here](https://github.com/cbaggers/varjo/issues/102#issuecomment-292459453) what we would have to do to make this happen.
