### ISSUE TITLE
Matrices cannot be constructed from a single scalar

### ISSUE THREAD

**Issue by mfiano** [cbaggers/varjo#206]
`(mat4 1.0)` should create an identity matrix, but there is no applicable method for creating a matrix from a scalar.

The OpenGL wiki states:

```
If a matrix is constructed with a single scalar value, then that value is used to initialize all the values along the diagonal of the matrix; the rest are given zeros. Therefore, mat4(1.0) is a 4x4 identity matrix.
```

**Comment by cbaggers** [comment]
Thanks for the report. Merging these matrix type constructor issues into https://github.com/cbaggers/varjo/issues/209
