### ISSUE TITLE
Compilation fails on vector with scalar math

### ISSUE THREAD

**Issue by djeis97** [cbaggers/varjo#28]
`vec4(1.0, 1.0, 1.0, 1.0) + 5` is valid GLSL, but varjo can't handle `(+ (v! 1.0 1.0 1.0 1.0) 5)`.

**Comment by cbaggers** [comment]
It's true. I didnt put and in...and purposefully too, there is something about it I didnt like.

I totally see the reason for wanting it though.

I could do a couple of things here:
- just add it baggers, stop being so picky
- make an optional package that adds all these overloads

Hmm I think I will do the first one.

**Comment by djeis97** [comment]
I probably never would have noticed it, to be honest, except that I'm porting a simplex noise shader that makes extensive use of it (https://github.com/ashima/webgl-noise/blob/master/src/noise3D.glsl).

**Comment by cbaggers** [comment]
@djeis97 This is coming, see issue #46 for how this will be implemented

**Comment by cbaggers** [comment]
It's in :)
