### ISSUE TITLE
varjo.tests system fails now

### ISSUE THREAD

**Issue by quicklisp** [cbaggers/varjo#38]
I get this:

    Unhandled SB-KERNEL:SIMPLE-PACKAGE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1003327663}>: no symbol named "DEFSHADER" in "VARJO"

**Comment by cbaggers** [comment]
Ouch, those tests are not ready for prime time. Removed for now
Thanks for the heads up and sorry for the inconvenience
