### ISSUE TITLE
Varjo doesn't build...

### ISSUE THREAD

**Issue by BradWBeer** [cbaggers/varjo#39]
I just pulled the latest version of Varjo and got this error:

 "no symbol named "V2!" in "RTG-MATH.BASE-VECTORS"

I also have the latest version of rtg-math.

**Comment by cbaggers** [comment]
I just pulled latest master of rtg-math and varjo & then ran `(asdf:load-system :varjo :force t :verbose t)` and had no problems.

If you're right then Im worried this might be an issue with the quicklisp released versions

**Comment by cbaggers** [comment]
Nope quicklisp version is fine too

**Comment by cbaggers** [comment]
closed as @BradWBeer was pulling from his own clone of rtg-math :)
