### ISSUE TITLE
Relax strict typechecking of if clauses when return value is discarded

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/varjo#42]
Whether the return value of an `if` form is used or discarded, Varjo insists on both true and false branches of an `if` clause returning the same type.  

If the value is discarded (in conversions of existing GLSL shaders, for instance), it is an unnecessary burden, often requiring the addition of a progn and a fake value just to match the other branch.

It would improve user experience to:
- relax the typechecking in cases where return values are ignored 
- allow dropping the `else` clause in such cases.

**Comment by cbaggers** [comment]
Thanks. 

Yeah if an `if` is not in the tail position of a progn the value is lost and we can safely allow inconsistent branch types

**Comment by cbaggers** [comment]
No need to track the tail position. Instead we will add the `or` type. This is going to be useful for compile-time-values anyway and it means we don't need any extra logic in the compilation environment

**Comment by cbaggers** [comment]
Aaand it worked :) https://github.com/cbaggers/varjo/commit/b699f69ca9a18f9095f1e274d200533ac3628849 `if` now handles both cases where it can and cannot resolve a single return type. `%if` has been removed.

 This is on the `feature-first-class-funcs` branch so it'll be a little while longer before it is merged in. It is there simply as the that branch has had a great deal of required refactoring done on it.

**Comment by cbaggers** [comment]
now waiting on https://github.com/cbaggers/varjo/issues/58
