### ISSUE TITLE
(break) in (for ...) is not usable

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/varjo#45]
While it does break out of the for loop, its value appears to be :void.  When embedded in `if` forms inside the loop (as it often is), this forces both branches of the if to be void. This may not always be possible.

This is related to the `if` issue I opened earlier.  Perhaps it is a larger issue: **breaking the chain of type-checking when return value is ignored, in all forms**.

Also, since (break) is a goto, the type enforced should be that of the destination scope, not the call site.  In other words, exiting the inner conditional does not matter:

``` lisp
 (for (i 0) (< i max-iterations) (++ i)
     (setf v (+ c (complex-square v)))
     (if (> (dot v v) 4.0) ;; when would be so much nicer here, don't you think?
         (progn
           (setf count i)
           (break)) ;; IF chokes here... Really, who cares about the if, or any value out of if here?
         0)) ;; Wrong! How does one specify a :void anyway?
```

**Comment by cbaggers** [comment]
Again related to #42 & #44

**Comment by cbaggers** [comment]
If you need something in the mean time, use 

```
(%if (> (dot v v) 4.0) ;; when would be so much nicer here, don't you think?
     (progn
       (setf count i)
       (break)))
```
as `%if` is like glsl's `if` in that it has no return type (it's a statement in glsl), whereas `if` is modelled after lisp's `if` and is an expression (more akin to glsl's `?` operator)

**Comment by cbaggers** [comment]
This looks promising :)

```
TESTS> (glsl-code
        (compile-vert ((a :int)) :450 nil
          (let ((count 0))
            (for (i 0) (< i 10) (setf i (+ i 1))
                 (when (< a 10)
                   (setf count i)
                   (break))))
          (v! 0 0 0 0)))
"#version 450

layout(location = 0) in int A;

void main() {
    int COUNT = 0;
    for (int I = 0;(I < 10);I = (I + 1)) {
        if ((A < 10))
        {
            COUNT = I;
            break;
        }
    }
    gl_Position = vec4(float(0),float(0),float(0),float(0));
}"
```
