### ISSUE TITLE
Add  +s and -s (vector and scalar operations)

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/varjo#46]
Just a reminder - please update Varjo when it's implemented in rtg-math.

**Comment by stacksmith** [comment]
I noticed it is already issue #28...

@cbaggers, I understand your reluctance, it is mathematically wrong... But it is consistent with (v4! 1.0), duplication of the existing values to match a wider vector...

**Comment by cbaggers** [comment]
Yeah, I'm softening up to this somewhat. The difference for now will be that I will use `+s` & `-s` which is in line with rtg-maths' api style.

One problem with just using `+` was that I have no way to make this fast on the cpu side as I would have to typecheck every argument at runtime.

I'm almost certain I'll just cave and support `+` in varjo and not in `rtg-math`. We currently have this for `*` when use on matrices and vectors too

**Comment by cbaggers** [comment]
fixed
