### ISSUE TITLE
Implement (with-slots ...) and (with-accessors ...)

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/varjo#47]
This is very useful in de-cluttering code, and very Lispy!

**Comment by cbaggers** [comment]
`/me learns of the existence of with-accessors` :|

Great idea though!

**Comment by cbaggers** [comment]
this relies on `symbol-macro-let` https://github.com/cbaggers/varjo/issues/54

**Comment by cbaggers** [comment]
We have all the parts for this now. Should be a quick fix tonight

**Comment by cbaggers** [comment]
Done! pushed to master & release
