### ISSUE TITLE
Pls clarify macros in Varjo

### ISSUE THREAD

**Issue by stacksmith** [cbaggers/varjo#51]
What happens to macros in Varjo?  I noticed v-defmacro, but can it do anything a Lisp macro can?   Can you destructure inside Varjo?  

If we had v-symbol-macrolet, (assuming destructuring is working) we could implement things like (with-slots...), etc.

**Comment by cbaggers** [comment]
Macros in Varjo are similar to the ones in lisp. Note that a Varjo macro isn't writing in Varjo's typed subset of lisp, it's just regular lisp. So here is `cond`

```
(v-defmacro cond (&rest clauses)
  `(if ,(caar clauses)
       ,(cadar clauses)
       ,@(when (rest clauses)
               `((cond ,@(rest clauses))))))
```

So far I only have v-defmacro & v-define-compiler-macro. The second is nearly identical except that it can shadow function names. I only really added it for completeness.

symbol macros make a lot of sense. I'm going to add a ticket for that

**Comment by cbaggers** [comment]
One downside of macros is that you have no type information when your are expanding. Which is a bit of a shame. When that is necessary I end up defining new special-forms but that is very hard as you have to care a lot about the internals of the compiler. I may look at some typed expansion mechanism in the future.

**Comment by cbaggers** [comment]
Feel free to ask more or close this ticket if this is enough
