### ISSUE TITLE
gl_position instead gl_Position

### ISSUE THREAD

**Issue by LinkFly** [cbaggers/varjo#65]
I learn example - moving-triangles.lisp (into cepl.examples project)
But vertex shader didn't compile. Reason is bag in vargo compilation - gl_position instead gl_Position (I checked it into debugger)

Shader generated:
----------
...
void main() {
    gl_position = CALC_POS(POSITION,I);
}

-------------------

But must be:
----------
...
void main() {
    gl_Position = CALC_POS(POSITION,I);
}

-------------------
(bug appear in Windows)
Please, fix it.

P.S. I do attaching script for to repeat bug...
```common-lisp
(in-package :varjo)

(print (slot-value 
	(first 
	 (slot-value 
	  (compile-stage (make-instance 'rolling-result)
			 '(((POSITION :VEC4)) ((CEPL.EXAMPLES::I :INT)) (:IUNIFORMS :VERTEX :|420|)
			   (PROGN (CEPL.EXAMPLES::CALC-POS POSITION CEPL.EXAMPLES::I)))
			 #'translate)
	  'compiled-stages)) 'glsl-code))
```

**Comment by cbaggers** [comment]
Please pull the latest from glsl-spec the fix is in there.

**Comment by LinkFly** [comment]
Ok, I saw it. Thank a lot!
