### ISSUE TITLE
issue when using the name 'texture'

### ISSUE THREAD

**Issue by jobez** [cbaggers/varjo#83]
i discovered this when poking around the texture example in cepl.examples

https://github.com/jobez/cepl.examples/commit/9b9fa05d0607c9effdca81b29b297b6668589918

if you try to run the example with the uniform named 'texture' you get the following error:

> Error compiling fragment-shader: 
0:20(22): error: no matching function for call to `texture(sampler2D, vec2)'; candidates are:
0:20(22): error:    vec4 texture(sampler1D, float)
0:20(22): error:    ivec4 texture(isampler1D, float)
0:20(22): error:    uvec4 texture(usampler1D, float)
0:20(22): error:    vec4 texture(sampler2D, vec2)
0:20(22): error:    ivec4 texture(isampler2D, vec2)
0:20(22): error:    uvec4 texture(usampler2D, vec2)
0:20(22): error:    vec4 texture(sampler3D, vec3)
0:20(22): error:    ivec4 texture(isampler3D, vec3)
0:20(22): error:    uvec4 texture(usampler3D, vec3)
0:20(22): error:    vec4 texture(samplerCube, vec3)
0:20(22): error:    ivec4 texture(isamplerCube, vec3)
0:20(22): error:    uvec4 texture(usamplerCube, vec3)
0:20(22): error:    float texture(sampler1DShadow, vec3)
0:20(22): error:    float texture(sampler2DShadow, vec3)
0:20(22): error:    float texture(samplerCubeShadow, vec4)
0:20(22): error:    vec4 texture(sampler1DArray, vec2)
0:20(22): error:    ivec4 texture(isampler1DArray, vec2)
0:20(22): error:    uvec4 texture(usampler1DArray, vec2)
0:20(22): error:    vec4 texture(sampler2DArray, vec3)
0:20(22): error:    ivec4 texture(isampler2DArray, vec3)
0:20(22): error:    uvec4 texture(usampler2DArray, vec3)
0:20(22): error:    vec4 texture(samplerCubeArray, vec4)
0:20(22): error:    ivec4 texture(isamplerCubeArray, vec4)
0:20(22): error:    uvec4 texture(usamplerCubeArray, vec4)
0:20(22): error:    float texture(sampler1DArrayShadow, vec3)
0:20(22): error:    float texture(sampler2DArrayShadow, vec4)
0:20(22): error:    float texture(samplerCubeArrayShadow, vec4, float)
0:20(22): error:    vec4 texture(sampler2DRect, vec2)
0:20(22): error:    ivec4 texture(isampler2DRect, vec2)
0:20(22): error:    uvec4 texture(usampler2DRect, vec2)
0:20(22): error:    float texture(sampler2DRectShadow, vec3)
0:20(22): error:    vec4 texture(sampler1D, float, float)
0:20(22): error:    ivec4 texture(isampler1D, float, float)
0:20(22): error:    uvec4 texture(usampler1D, float, float)
0:20(22): error:    vec4 texture(sampler2D, vec2, float)
0:20(22): error:    ivec4 texture(isampler2D, vec2, float)
0:20(22): error:    uvec4 texture(usampler2D, vec2, float)
0:20(22): error:    vec4 texture(sampler3D, vec3, float)
0:20(22): error:    ivec4 texture(isampler3D, vec3, float)
0:20(22): error:    uvec4 texture(usampler3D, vec3, float)
0:20(22): error:    vec4 texture(samplerCube, vec3, float)
0:20(22): error:    ivec4 texture(isamplerCube, vec3, float)
0:20(22): error:    uvec4 texture(usamplerCube, vec3, float)
0:20(22): error:    float texture(sampler1DShadow, vec3, float)
0:20(22): error:    float texture(sampler2DShadow, vec3, float)
0:20(22): error:    float texture(samplerCubeShadow, vec4, float)
0:20(22): error:    vec4 texture(sampler1DArray, vec2, float)
0:20(22): error:    ivec4 texture(isampler1DArray, vec2, float)
0:20(22): error:    uvec4 texture(usampler1DArray, vec2, float)
0:20(22): error:    vec4 texture(sampler2DArray, vec3, float)
0:20(22): error:    ivec4 texture(isampler2DArray, vec3, float)
0:20(22): error:    uvec4 texture(usampler2DArray, vec3, float)
0:20(22): error:    vec4 texture(samplerCubeArray, vec4, float)
0:20(22): error:    ivec4 texture(isamplerCubeArray, vec4, float)
0:20(22): error:    uvec4 texture(usamplerCubeArray, vec4, float)
0:20(22): error:    float texture(sampler1DArrayShadow, vec3, float)
0:20(22): error: operands to arithmetic operators must be numeric

> #version 430
> 
> smooth in vec2 out1076;
> 
> layout(location = 0) out vec4 output_color1077;
> 
> uniform sampler2D texture;
> uniform float count;
> uniform vec4 pos_offset;
> 
> void main() {
>     float RIP_SIZE = 0.02f;
>     vec2 CENTRE = vec2(0.0f,0.0f);
>     float DAMP = 0.6f;
>     float PEAKS = 9.0f;
>     vec2 DIF = (out1076 - CENTRE);
>     float DIST = dot(DIF,DIF);
>     float HEIGHT = ((cos((count + (DIST * PEAKS))) + sin((count - (out1076.y * PEAKS)))) / 2.0f);
>     vec2 RIP_OFFSET = ((normalize(DIF) * RIP_SIZE) * (HEIGHT * DAMP));
>     output_color1077 = (texture(texture,(RIP_OFFSET + out1076)) + vec4((-0.2f * HEIGHT),(-0.2f * HEIGHT),0.0f,0.0f));;
> }
>    [Condition of type SIMPLE-ERROR]

>   0: (CEPL.PIPELINES::MAKE-SHADER :FRAGMENT-SHADER "#version 430 ..)
>   1: (CEPL.PIPELINES::%COMPILE-LINK-AND-UPLOAD RIPPLE-WITH-WOBBLE ((:VERTEX . #<GPU-FUNCTION (TEX-VERT G-PT)>) (:FRAGMENT . #<GPU-FUNCTION (TEX-FRAG :VEC2)>)))
>   2: ((LABELS #:|init1073|))
>   3: (RIPPLE-WITH-WOBBLE #<unused argument> #<CEPL:BUFFER-STREAM (2) :LENGTH 3> :POS-OFFSET #(0.0 0.0 0.0 0.0) :COUNT 0.0 :TEXTURE #<SAMPLER-2D #<TEXTURE-2D (64x64)>>)
>   4: (STEP-DEMO)
>   5: (RUN-LOOP)
>   6: (SB-INT:SIMPLE-EVAL-IN-LEXENV (RUN-LOOP) #<NULL-LEXENV>)
>   7: (EVAL (RUN-LOOP))
>   8: ((LAMBDA NIL :IN SWANK:INTERACTIVE-EVAL))

**Comment by cbaggers** [comment]
Ouch! looks like am not handling names properly there. Thanks for reporting this.

**Comment by cbaggers** [comment]
Fixed
