### ISSUE TITLE
No way to declare layout specifiers for geometry shaders

### ISSUE THREAD

**Issue by djeis97** [cbaggers/varjo#85]
So I finally got around to working on this again- I've updated the inline-glsl shader to work with the latest quicklisp version and (hopefully tonight) I'm going to test it against master.
https://github.com/djeis97/bezier

In order to work as a geometry shader, you need to have:
 ```glsl
layout(<vertex shader output type>) in;
layout(<geomtry shader output type>, max_verticies= <maximum number of calls to EmitVertex();>) out;
```

In my example, since I'm just drawing lines for simplicity, this is:
```glsl
layout(lines) in;
layout(line_strip, max_verticies=5) out;
```

As there's no clear way to declare those, unless I've totally missed something, the only way to create geometry shaders is to use inline glsl.

**Comment by cbaggers** [comment]
Note to self: https://github.com/cbaggers/varjo/issues/86

**Comment by cbaggers** [comment]
Fixed in master. Syntax is ` (declare (output-primitive :kind :triangle-strip :max-vertices 3))`

You can see it's use [here](https://github.com/cbaggers/varjo/blob/master/tests/build-tests.lisp#L227)
