### ISSUE TITLE
def-glsl-stage wants symbols for uniform args instead of strings

### ISSUE THREAD

**Issue by djeis97** [cbaggers/varjo#91]
```lisp
(def-glsl-stage (("color" (:vec4 (*)) &uniform ("transform" :mat4) &context :330 :geometry)
  "..."
  (("color_out" :vec4)))
```
Complains that `"transform"` is not a symbol, but replacing it with `transform` as in
```lisp
(def-glsl-stage (("color" (:vec4 (*)) &uniform (transform :mat4) &context :330 :geometry)
  "..."
  (("color_out" :vec4)))
```
makes opengl complain because the symbol is not transformed into a valid identifier when compiled (not that having a symbol there makes much sense regardless).

**Comment by djeis97** [comment]
Took me more than too long to realize that there'd be no good way to pass a string-named uniform arg to map-g... Now I'm really not sure how to handle this.

One possibility would be to add a syntax that would allow specifying both the lisp and glsl name for a uniform, but I suspect that that might cause problems if some other func defines a uniform with the same lisp name.

**Comment by cbaggers** [comment]
the code for `def-glsl-stage` should be upcasing the string name and then interning it, so `"transform"` would be `:transform` in map-g. Is that not working?

**Comment by cbaggers** [comment]
note to self: this is a cepl issue

**Comment by djeis97** [comment]
Not sure what I was doing Monday, but I just pulled everything from master and tried again and it worked.

**Comment by cbaggers** [comment]
Cool
