### ISSUE TITLE
mat4 takes wrong number of arguments

### ISSUE THREAD

**Issue by podiki** [cbaggers/varjo#99]
Unable to make a `mat4` when calling `(m! 1 2 3...16)`. In [language/functions.lisp](https://github.com/cbaggers/varjo/blob/79af50ef1f462ec81167d33b980d2ecc68441f7d/language/functions.lisp#L220) the definition for `m!` with 16 arguments then uses 17 in the actual code. Fixes this allows a GPU function to compile that uses `m!`, though I don't know the code base well so I'm not sure if the definition needs to be updated elsewhere (or bug in some generating script).

**Comment by podiki** [comment]
Additionally, it doesn't seem like there is support for calling `(m! 1.0)` to make e.g. an identity matrix.

**Comment by cbaggers** [comment]
Well.. that's a tad embarrassing. Thanks for the heads up. I'll get on that now

**Comment by cbaggers** [comment]
Fixed on master

**Comment by cbaggers** [comment]
Oh and regarding (m! 1.0). It isnt clear from the call what size the matrix should be. I do have similar functions for vectors (v4! 1.0) so I should add sized constructors for the matrices too. Thanks for pointing that out :)

**Comment by podiki** [comment]
Well I embarrassingly had to count too many times to see if I was going crazy.

Yes, I realized there is ambiguity in the size for some matrices called like that. This would also be the case in wanting to make a mat4 by specifying the diagonal only (I think that is in GLSL).
